typedef enum {
    SIP_METHOD_INVITE,
    SIP_METHOD_ACK,
    SIP_METHOD_OPTIONS,
    SIP_METHOD_BYE,
    SIP_METHOD_CANCEL,
    SIP_METHOD_REGISTER,
    SIP_METHOD_INFO,
    SIP_METHOD_PRACK,
    SIP_METHOD_SUBSCRIBE,
    SIP_METHOD_NOTIFY,
    SIP_METHOD_UPDATE,
    SIP_METHOD_MESSAGE,
    SIP_METHOD_REFER,
    SIP_METHOD_PUBLISH,
} SIP_METHOD;

#define SIP_METHOD_NAME_NONE "NONE"
#define SIP_METHOD_NAME_REGISTER "REGISTER"
#define SIP_METHOD_NAME_INVITE "INVITE"
#define SIP_METHOD_NAME_ACK "ACK"
#define SIP_METHOD_NAME_OPTIONS "OPTIONS"
#define SIP_METHOD_NAME_BYE "BYE"
#define SIP_METHOD_NAME_CANCEL "CANCEL"
#define SIP_METHOD_NAME_INFO "INFO"
#define SIP_METHOD_NAME_PRACK "PRACK"
#define SIP_METHOD_NAME_SUBSCRIBE "SUBSCRIBE"
#define SIP_METHOD_NAME_NOTIFY "NOTIFY"
#define SIP_METHOD_NAME_UPDATE "UPDATE"
#define SIP_METHOD_NAME_MESSAGE "MESSAGE"
#define SIP_METHOD_NAME_REFER "REFER"
#define SIP_METHOD_NAME_PUBLISH "PUBLISH"

char *MethodMap2String(SIP_METHOD method);
